database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:mem:sample
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create

enableOpenApiSpec: true

logging:
  level: INFO
  loggers:
    org.example: DEBUG
